env:
  browser: false
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  # std: true
  # hk: true
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: {}
